contracts/IbetShare.sol, tests/conftest.py, tests/test_ibetshare.py
=> feat: add transfer approval functions

contracts/IbetShare.sol, tests/test_ibetshare.py
=> emit transfer event

contracts/IbetShare.sol, tests/test_ibetshare.py, tests/utils.py
=> feat: add principal value

contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol
=> fix: return true on success

README.md
=> feat: add branching model

contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, interfaces/IbetExchangeInterface.sol, tests/exchange/test_IbetExchange.py
=> feat: add ibet exchange interface

contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, interfaces/IbetExchangeInterface.sol, tests/exchange/test_IbetEscrow.py, tests/exchange/test_IbetExchange.py
#338 
- Added an event to IbetExchangeInterface on change of holder.
- Implemented events in IbetEscrow and IbetExchange.
=> feat: add holder changed event

README.md
=> feat: add explanations about ibet contracts

contracts/exchange/IbetExchange.sol, contracts/token/IbetShare.sol, contracts/token/IbetStraightBond.sol, tests/exchange/test_IbetEscrow.py, tests/exchange/test_IbetExchange.py, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
=> feat: change check logic when msg.sender is tradableExchange

contracts/exchange/IbetExchange.sol, tests/exchange/test_IbetExchange.py
=> feat: add force cancel function

contracts/exchange/IbetExchange.sol, tests/exchange/test_IbetExchange.py
=> feat: revert the balance to the pre-order state

contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol, interfaces/IbetSecurityTokenInterface.sol, interfaces/IbetStandardTokenInterface.sol, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
=> feat: ibet security token interface

contracts/exchange/EscrowStorage.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetShare.sol, contracts/token/IbetStraightBond.sol, interfaces/IbetSecurityTokenInterface.sol, tests/conftest.py, tests/exchange/test_IbetSecurityTokenEscrow.py
=> feat: security token escrow

scripts/deploy_shared_contract.py, scripts/upgrade_ibet_security_token_escrow.py, scripts/upgrade_ibet_security_token_escrow.sh
- Add deploy tools for ibetSecurityTokenEscrow
=> feat: add deploy script

contracts/token/IbetShare.sol, contracts/token/IbetStraightBond.sol, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
=> backward compatible calls

contracts/exchange/IbetSecurityTokenEscrow.sol, tests/exchange/test_IbetSecurityTokenEscrow.py
- Added an event to IbetSecurityTokenEscrow.
- ApplyForTransfer -> CancelTransfer -> ApproveTransfer -> FinishTransfer
```solidity
/// Event: 移転申請
event ApplyForTransfer(
uint256 indexed escrowId,
address indexed token,
address from,
address to,
uint256 value,
string data
);
/// Event: 移転申請取消
event CancelTransfer(
uint256 indexed escrowId,
address indexed token,
address from,
address to
);
/// Event: 移転承認
event ApproveTransfer(
uint256 indexed escrowId,
address indexed token,
string data
);
/// Event: 移転完了
event FinishTransfer(
uint256 indexed escrowId,
address indexed token,
address from,
address to,
string data
);
```
=> feat: add FinishTransfer event

README.md, brownie-config.yaml
=> feat: fixing the solc version

tests/brownie_utils.py
=> feat: Change to wait_for_transaction_receipt

contracts/ledger/PersonalInfo.sol, tests/ledger/test_PersonalInfo.py
=> feat: personalInfo force registration

contracts/exchange/EscrowStorage.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/utils/E2EMessaging.sol, tests/exchange/test_IbetSecurityTokenEscrow.py
close #372 
Transfer from address A to address B
1. createEscrow
- Escrow created (balance at address A)
- Create ApplicationForTransfer (escrowFinished= false)
- Emit ApplyForTransfer event
2. finishEscrow
- Update the escrow completion status of the ApplicationForTransfer (escrowFinished= true)
- Update (deactivate) Escrow
3. approveTransfer
- Ownership moves from address A to address B
1. createEscrow
- Escrow creation
2. finishEscrow
- Ownership moves from address A to address B
- Update (deactivate) Escrow
=> feat: Change the timing of transfer approval in escrow contract

README.md, brownie-config.yaml, contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol
- upgrade solidity
- upgrade openzeppelin-contracts
=> feat: upgrade openzeppelin

scripts/deploy_shared_contract.sh
=> fix: a bug in the deployment script

docs/Errors.md
**Fixed only document**
Related to #386
=> fix: error code document

README.md, brownie-config.yaml, contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol
=> feat: upgrade solc and openzeppelin

Dockerfile, tests/Dockerfile
=> feat: upgrade python

interfaces/IbetStandardTokenInterface.sol
=> feat: Add detailed explanation of "status"

README.md, README_JA.md
=> feat: Add japanese document

contracts/token/IbetShare.sol, contracts/token/IbetStraightBond.sol, contracts/utils/Errors.sol, docs/Errors.md, interfaces/IbetSecurityTokenInterface.sol, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
=> feat: Spec change of lock function of ST

contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, tests/conftest.py, tests/exchange/test_IbetEscrow.py, tests/exchange/test_IbetSecurityTokenEscrow.py
Close #405
- I was wondering if it should be modified to return the escrow ID of the error when it occurs.
- If it should return error escrow id as revert message, "custom error" could be used.
- https://blog.soliditylang.org/2021/04/21/custom-errors/
=> add: add bulkFinishEscrow

Dockerfile, tests/Dockerfile
=> Upgrade Alpine to 3.17

README.md, README_JA.md, brownie-config.yaml, contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol
=> Upgrade solc to 0.8.19

README.md, README_JA.md, brownie-config.yaml, contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetCoupon.sol, contracts/token/IbetERC20.sol, contracts/token/IbetERC721.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol, tests/token/test_IbetERC20.py, tests/token/test_IbetERC721.py
close #412 
Unit tests are implemented only for parts that are self-implemented.
=> Add ERC20/721 support

Dockerfile, README.md, README_JA.md, brownie-config.yaml, contracts/exchange/IbetEscrow.sol, contracts/exchange/IbetExchange.sol, contracts/exchange/IbetSecurityTokenEscrow.sol, contracts/token/IbetCoupon.sol, contracts/token/IbetERC20.sol, contracts/token/IbetERC721.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol, data/networks.yml, requirements.lock, requirements.txt, tests/Dockerfile
=> Upgrade OpenZeppelin and support berlin EVM

README.md, README_JA.md, brownie-config.yaml
=> Bump solidity

README.md, README_JA.md, brownie-config.yaml
Upgrade Solc to the latest version.
=> Bump solc to v0.8.23

Dockerfile, README.md, README_JA.md, tests/Dockerfile
Upgrade alpine linux to version 3.19
=> Upgrade alpine to v3.19

package-lock.json, poetry.lock, pyproject.toml
The bug in eth-brownie that caused the problem in the PR below has been fixed, so I reverted the installation of eth-brownie.
- https://github.com/BoostryJP/ibet-SmartContract/pull/429
=> Bump eth-brownie

contracts/token/IbetCoupon.sol, contracts/token/IbetMembership.sol, contracts/token/IbetShare.sol, contracts/token/IbetStandardToken.sol, contracts/token/IbetStraightBond.sol, contracts/utils/Errors.sol, docker-compose.yml, interfaces/IbetSecurityTokenInterface.sol, interfaces/IbetStandardTokenInterface.sol, tests/token/test_IbetCoupon.py, tests/token/test_IbetMembership.py, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
close #446 
```solidity
/// @notice 強制移転（一括）
/// @param _fromList 移転元アドレスのリスト
/// @param _toList 移転先アドレスのリスト
/// @param _valueList 移転数量のリスト
/// @return success 処理結果
function bulkTransferFrom(
address[] calldata _fromList,
address[] calldata _toList,
uint256[] calldata _valueList
) public virtual returns (bool success);
```
```solidity
/// @notice 追加発行（一括）
/// @param _targetAddressList 追加発行対象の残高を保有するアドレスのリスト
/// @param _lockAddressList 資産ロック先アドレスのリスト
/// @param _amounts 追加発行数量のリスト
function bulkIssueFrom(
address[] calldata _targetAddressList,
address[] calldata _lockAddressList,
uint256[] calldata _amounts
) public virtual;
```
```solidity
/// @notice 償却/消却（一括）
/// @param _targetAddressList 償却対象の残高を保有するアドレスのリスト
/// @param _lockAddressList 資産ロック先アドレスのリスト
/// @param _amounts 償却数量のリスト …
```
=> Add bulk functions

docs/Errors.md
=> Update error code doc

.github/auto_assign.yml, .github/workflows/auto-assign.yml, contracts/exchange/IbetSecurityTokenDVP.sol, contracts/utils/Errors.sol, docs/Errors.md, package-lock.json, poetry.lock, tests/Dockerfile_unittest, tests/exchange/test_IbetSecurityTokenDVP.py
- Close #450 
- I also added a workflow to automatically assign reviewers to PRs.
=> DVP: Partial withdrawal

package-lock.json, poetry.lock
- I performed version upgrades for **eth-brownie** and other dependencies.
=> Bump packages

contracts/token/IbetShare.sol, contracts/token/IbetStraightBond.sol, contracts/utils/Errors.sol, docs/Errors.md, interfaces/IbetSecurityTokenInterface.sol, tests/token/test_IbetShare.py, tests/token/test_IbetStraightBond.py
I implemented the forceLock function for `ibetSecurityToken`.
- Close #460
- Define the `forceLock` function in ibetSecurityTokenInterface.
- Implemented the `forceLock` function in the ibetStraightBond and ibetShare contracts.
=> Add forceLock function

.github/dependabot.yml
This pull request introduces a `.github/dependabot.yml` configuration file to automate dependency updates for the project. The configuration supports three ecosystems: `uv`, `npm`, and `github-actions`, with weekly update schedules.
- Close #464
* Added `.github/dependabot.yml` to enable automated dependency updates for the following ecosystems:
- [`uv`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R27): Updates direct dependencies weekly on Mondays at midnight.
- [`npm`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R27): Updates direct dependencies weekly on Mondays at midnight.
- [`github-actions`](diffhunk://#diff-dd4fbda47e51f1e35defb9275a9cd9c212ecde0b870cba89ddaaae65c5f3cd28R1-R27): Updates direct …
=> Add dependabot configuration for automated dependency updates

package-lock.json, package.json
This pull request makes a minor update to the `package.json` file, downgrading the `hardhat` development dependency from version 3.x to version 2.26.3. This change likely addresses compatibility or stability concerns.
None
- Downgrade hardhat to v2
=> Downgrade hardhat version to 2.26.3 in package.json
